### ISSUE TITLE
Cannot Decode CLLocationWrapper From FireStore

### ISSUE THREAD

**Issue by JoseSanchezMirandaRos** [visskiss/CLLocation-Codable#2]
Hello,

I am trying to decode a CLLocationWrapper property called "startLocation" that's inside my custom codable class. It keeps giving me this issue:
`keyNotFound(CodingKeys(stringValue: "coordinate", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "startLocation", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"coordinate\", intValue: nil) (\"coordinate\").", underlyingError: nil))`

If I delete the` let coordinateWrapper = try container.decode(CLLocationCoordinate2DWrapper.self, forKey: .coordinate)` then the next property to be decoded fails and so on... 

I am using firebase and I have no problem Encoding and saving to Firebase but the problem is when I try to decode it. One thing I've noticed is that the "location" key doesn't seem to be referenced anywhere, not sure if this could be related... 

This is how the the container looks before it fails:
<img width="472" alt="Screenshot 2023-09-15 at 6 26 54 PM" src="https://github.com/visskiss/CLLocation-Codable/assets/10212034/c9612c52-d01c-474d-8355-f627ce811b5c">

And this is how it's is stored in Firebase:
<img width="570" alt="Screenshot 2023-09-15 at 6 29 30 PM" src="https://github.com/visskiss/CLLocation-Codable/assets/10212034/47668bc6-3b53-4080-8eb5-a79ca2b7a128">

Any idea what could be going on? any help is appreciated!

**Comment by visskiss** [comment]
Can you please include a code snippet with comments so I can see surrounding context. From your description, it seems like there's an error with the object that contains the CLLocation.

**Comment by JoseSanchezMirandaRos** [comment]
Absolutely! thanks for the prompt response.

Here's where how initialize the Object and save it to firebase with no issues:

<img width="1322" alt="Screenshot 2023-09-15 at 7 00 13 PM" src="https://github.com/visskiss/CLLocation-Codable/assets/10212034/02f4da5d-da33-4e13-9702-bcce41b11aae">

Here's when I try to retrieve the object using the Firebase Decoder which is the .data method you see here:

<img width="670" alt="Screenshot 2023-09-15 at 7 05 07 PM" src="https://github.com/visskiss/CLLocation-Codable/assets/10212034/980c658f-b01e-461a-aa9b-7c7c3d3da2c1">

This is how I declare the properties in my custom object:

<img width="335" alt="Screenshot 2023-09-15 at 7 02 55 PM" src="https://github.com/visskiss/CLLocation-Codable/assets/10212034/d0415346-b29f-41c4-8582-7879d225dbc4">

and then it fails when decoding the location. Hope this gives you more context!

**Comment by visskiss** [comment]
You are getting the same error when you delete that line because the value is nil for the entire location object.  Your custom object will need to have CLLocations, not CLLocationWrappers, as the properties. If your custom object conforms to Codable, then you will need to write your own init with coder that unwraps the locations as locationwrappers and then sets the properties to the location property of that wrapper. If that makes sense, make sure that's what you are doing. CLLocationWrapper is not Encodable, but is only Decodable. Vice versa for CLLocation

**Comment by JoseSanchezMirandaRos** [comment]
Thanks for the support! Yeah, I was missing the custom init from coder for the keys. I made a terrible assumption that it'll work without them. Thanks so much and great work!

**Comment by visskiss** [comment]
Glad you solved this. I am surprised it compiled without explicitly requiring the init.
